/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Message;
import io.swagger.model.SubmitRequest;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-09T11:43:32.706Z")

@Api(value = "createEmprunt", description = "the createEmprunt API")
public interface CreateEmpruntApi {

    @ApiOperation(value = "demande d emprunt", notes = "en entrée les informations sur le livre et l'emprunteur", response = Message.class, tags={ "Emprunt", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "La soumission est un success", response = Message.class) })
    
    @RequestMapping(value = "/createEmprunt",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Message> createEmpruntPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SubmitRequest submitParam);

}
